### ISSUE TITLE
How to use karma with code-coverage?

### ISSUE THREAD

**Issue by moslemezzati** [codacy/node-codacy-coverage#25]
Hi, my `lcov` file is create by karma and I dont know how send the `lcov` file as parameter to codacy-coverage.js file because there is no document for karma and codacy-coverage. 
how do I use karma to codacy coverage?

**Comment by machadoit** [comment]
Hi, did you try the normal usage? Putting the lcov content in ./node_modules/.bin/codacy-coverage?

**Comment by moslemezzati** [comment]
How could I do that? is there an example?

**Comment by machadoit** [comment]
You can check how we handle our coverage in https://github.com/codacy/node-codacy-coverage/blob/master/circle.yml

You can pass the conent of the lcov file to codacy-coverage with:
cat ./coverage/lcov.info | node ./bin/codacy-coverage.js

**Comment by moslemezzati** [comment]
I'd done but it showed me this error `input is not a tty`

**Comment by rtfpessoa** [comment]
I am not sure about the problem with the tty.

But can you try:
```sh
npm install codacy-coverage --save-dev
cat /path/to/your/lcov | ./node_modules/.bin/codacy-coverage
```

What OS are you using?

**Comment by moslemezzati** [comment]
yes I shows me no error this time but after execute this commands:
`cat shippable/codecoverage/report-lcov/lcov.info | ./node_modules/.bin/codacy-coverage`
It shows nothing and my branch still clean, what should I do manually to see coverage report on codacy dashboard?

**Comment by moslemezzati** [comment]
BTW I use `Windows 8.1`

**Comment by rtfpessoa** [comment]
@moslemezzati can you send a support ticket so we can check your project?

**Comment by moslemezzati** [comment]
@rtfpessoa What is "support ticket" do you mean "Project Token"? If it is I'll sent it to you

**Comment by rtfpessoa** [comment]
No. You should never share any tokens with other people.
As we mention in the README, you should always keep it private.

About the support ticket: after you login with your account on Codacy, you should be able to see a question mark in the left lower corner of your screen. Or if you click in your account photo in the top right corner you have an option called support.

That way we can check your account and have more information.

**Comment by moslemezzati** [comment]
OK thanks I did it

**Comment by julmot** [comment]
@machadoit I think a karma reporter would be the solution here. I'm searching for it too.

**Comment by moslemezzati** [comment]
I solved the problem actually there is 2 problem first reporter file must be in a certain structure and second there is no good document to explain this simple point. It's shame!

**Comment by kavvak** [comment]
@moslemezzati What was your solution exactly? Cause I am using karma/webpack and when I send the coverage to Codacy it shows me this error:

X Oops! We weren't able to validate your report. Ping us on the support chat and we will help you figure it out.
What might be wrong?
Outdated reporter: Always make sure you are running an up-to-date version of the reporter.
Inconsistent file paths: Depending on your project structure, we may be unable to automatically detect the files identified in your coverage report. The reporters have special options to normalise the project root folder, check their documentation.

**Comment by a11smiles** [comment]
@kavvak @moslemezzati i'm having the same problem with karma/webpack

**Comment by rtfpessoa** [comment]
@a11smiles @kavvak The main problem here is usually the paths that your report has coverage to.

Since you use webpack to pre-process the files before running coverage you usually also change the file paths in the system. Something like `src/my/path/to/file.js` ends up in something like `another/path/to/file.js` and since Codacy is running the analysis for `src/my/path/to/file.js` we wont be able to pair coverage with your files. To make this work you maybe can work around it by replacing the paths.

Can this be your problem?

**Comment by a11smiles** [comment]
one of my source files is: `/home/travis/build/username/project/src/test.ts`

```
[trace] "2016-11-12T06:03:47.394Z"  'Successfully parsed /home/travis/build/username/project/src/test.ts'

[trace] "2016-11-12T06:03:47.397Z"  { total: 100,
  fileReports: 
   [ { filename: 'src/test.ts', coverage: [Object], total: 100 },
     { filename: 'src/polyfills.ts', coverage: [Object], total: 100 },
     { filename: 'src/app/app.component.ts',
       coverage: [Object],
       total: 100 } ] }
```

I have tried using the prefix parameter and adding `/home/travis/build/username/project/` but that doesn't work either.

As nice as everything else is with Codacy, you would think:    

1. Codacy would be smart enough to extract Travis CI's path just like the other coverage tools (Coveralls, CodeCov, etc.)  
2. Your support team would be more responsive.  I reached out yesterday via the 'chat' and still haven't heard anything.

**Comment by a11smiles** [comment]
Do you, perhaps, not support typescript?

**Comment by rtfpessoa** [comment]
@a11smiles we do not support Typescript at the moment. But it is in our short roadmap and should be released soon. Check the supported languages here: https://support.codacy.com/hc/en-us/articles/207994735-Supported-Languages

**Comment by a11smiles** [comment]
@rtfpessoa Thanks for letting me know about TypeScript.  Regarding my file paths, how does everything look in the debug sample that I sent?  Do I need to do anything to tweak it?

**Comment by a11smiles** [comment]
I want to be prepared when you do release support :)

**Comment by rtfpessoa** [comment]
Your report looks OK. The only problem now seems to be the unsupported language.

We will notify you when TS is supported.
