### ISSUE TITLE
No coverage displayed after sending valid lcov report

### ISSUE THREAD

**Issue by vcernomschi** [codacy/node-codacy-coverage#26]
No coverage displayed after sending valid lcov report
![screen shot 2016-05-13 at 2 22 55 pm](https://cloud.githubusercontent.com/assets/10863276/15246570/77bba592-1916-11e6-83e1-6242aaf9fb37.png)

Prerequisities: 
  - codacy-coverage@1.1.3
  - istanbul 0.4.0 to generate reports
  - istanbul-combine 0.3.0 to combine reports

Steps to reproduce:
1. Generate lcov report by using istanbul and istanbul-combine.
2. Send it to codacy (CODACY_PROJECT_TOKEN was configured in travis CI): 
`cat ${COVERAGE_PATH}"/lcov.info" | codacy-coverage --debug`
3. Check command result for debug ( `[debug] "2016-05-13T09:00:01.658Z"  'Successfully sent coverage'`)
4. Check result on Codacy Web page (https://www.codacy.com/app/MitocGroup/deep-framework/dashboard): 

Expected result: coverage info is displayed.
Actual result:  coverage info is not displayed. After click on `Setup Coverage` button the following information is displayed:
```
 Oops! We weren't able to validate your report. Ping us on the support chat and we will help you figure it out.
```
[lcov.info.txt](https://github.com/codacy/node-codacy-coverage/files/263103/lcov.info.txt)

Please refer to the attached coverage file (lcov.info.txt) that is generated by instanbul.

Please refer to the full TRAVIS CI log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/129941728/log.txt

**Comment by rtfpessoa** [comment]
Hi @vcernomschi ,

From what I can check, your project has files named like `src/path1/path2/file.js` but the reports are being sent for files named `src/path1/compile/path2/file.js`.

If the coverage is sent for a different path we cannot associate it with the original file on our side.

If you cannot fix this at the coverage tool level, maybe you can sed replace the paths.

**Comment by vcernomschi** [comment]
Thanks @rtfpessoa! I will update and check one more time.

**Comment by devs-deep** [comment]
@rtfpessoa: It doesn't display coverage for deepify, deep-package-manager projects. 

From log I see that it sent and had valid path:
```
[debug] "2016-05-18T10:13:12.135Z"  'Sending coverage'
[debug] "2016-05-18T10:13:12.674Z"  'Successfully sent coverage'
TN:
SF:/home/travis/build/MitocGroup/deepify/src/lib/Exception/Exception.js
[log.txt](https://github.com/codacy/node-codacy-coverage/files/270426/log.txt)

```

**Comment by devs-deep** [comment]
Hi, just wondering if there are any reasons. Because issue is still reproducible and affects 3 projects.

**Comment by machadoit** [comment]
Hi @devs-deep,

Can you please explain your issue in Codacy website support, and specify which projects have the issue? You will get a better support that way.

Thank you
