### ISSUE TITLE
Everything was working fine last week, then started 404'ing for coverage posting. Charts say no data found for coverage, issues, etc.

### ISSUE THREAD

**Issue by jeffbski** [codacy/node-codacy-coverage#28]
I had everything working fine, I was seeing coverage updates and a chart by commits, then I noticed that the chart now says no data. 

I guess I should also mention that I'm not seeing other things in the charts either like issues. Those were working as well and everything just stopped all at once. 

In looking at travis-ci logs, I can see that coverage was generated and registered 100%, but now it no longer is getting submitted successfully by codacy-coverage module. I can see that the CODACY_PROJECT_TOKEN is still set in my travis environment variables. 

I don't believe that anything changed regarding how I am doing coverage and how things are being submitted to codacy.

Can you help me understand what is broken with my project?
https://www.codacy.com/app/jeff-barczewski/redux-logic/dashboard

My npm script that is executed on travis is:
```
    "test:cov-codacy": "cross-env NODE_ENV=test nyc --reporter=lcov --reporter=text mocha test --recursive && cat coverage/lcov.info | codacy-coverage",
```

The output from the run is below:

```
... passing test output snipped
128 passing (1s)
--------------------------|----------|----------|----------|----------|----------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------|----------|----------|----------|----------|----------------|
All files                 |      100 |      100 |      100 |      100 |                |
 createLogic.js           |      100 |      100 |      100 |      100 |                |
 createLogicAction$.js    |      100 |      100 |      100 |      100 |                |
 createLogicMiddleware.js |      100 |      100 |      100 |      100 |                |
 index.js                 |      100 |      100 |      100 |      100 |                |
 logicWrapper.js          |      100 |      100 |      100 |      100 |                |
--------------------------|----------|----------|----------|----------|----------------|
[error] "2016-08-14T04:33:11.911Z"  'Status Code [404] - Error [{"error":"not found"}]'
[error] "2016-08-14T04:33:11.913Z"  'Error sending coverage'
[error] "2016-08-14T04:33:11.913Z"  Error: Expected Successful Status Code, but got [404]
    at /home/travis/build/jeffbski/redux-logic/node_modules/codacy-coverage/lib/reporter.js:70:35
    at tryCatcher (/home/travis/build/jeffbski/redux-logic/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/jeffbski/redux-logic/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/travis/build/jeffbski/redux-logic/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/travis/build/jeffbski/redux-logic/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/travis/build/jeffbski/redux-logic/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/travis/build/jeffbski/redux-logic/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/travis/build/jeffbski/redux-logic/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
The command "npm run test:cov-codacy" exited with 0.
```

**Comment by rtfpessoa** [comment]
Hi @jeffbski, 

Sorry for the delay getting back to you. If you can please open a ticket inside Codacy.
So we can check more information.

In the meanwhile, what is the version of the package you are using?
I recommend you to update to version 2.0.0 if you do not have it yet.

**Comment by jeffbski** [comment]
Yes I am using the latest 2.0.0. Where do I open a ticket? Is that the menu item for feedback or is there something else?

Thanks,

Jeff

**Comment by rtfpessoa** [comment]
After you sign in, you click in the floating question mark in the lower right corner.

**Comment by machadoit** [comment]
Issue solved on website support

**Comment by rubenspgcavalcante** [comment]
I'm with the same problem. @machadoit can you post the solution here?

**Comment by machadoit** [comment]
Hi @rubenspgcavalcante, please contact the website support, it is much easier to assist you from there. Please provide us any useful information via the Codacy website support, for which project/branch are you having issues, and the commands that you are running to send the coverage to us.
