### ISSUE TITLE
Help with sending coverage data 

### ISSUE THREAD

**Issue by beeeku** [codacy/node-codacy-coverage#43]
Hi, I have generated my test coverage using jest --coverage command. But I am lost at sending them to codacy. Can anyone help me out with the exact steps I have to do to send the coverage to codacy ?

**Comment by pedrorijo91** [comment]
Have you looked at the README file? https://github.com/codacy/node-codacy-coverage#usage

This is how we send coverage for this project: https://github.com/codacy/node-codacy-coverage/blob/master/circle.yml#L11

**Comment by beeeku** [comment]
I have looked at the readme before but didn't understand it. But after you left a comment I managed to figure out to send the coverage. 
Steps were from - 

1. Generate coverage from your favourite testing tool. Mine is jest so did a "jest --coverage" that generated all coverage.
2. Install node-codacy-coverage with either npm/yarn.
3. To send out the report you need to add codacy project token to your project either via .env file or in the next command.
4.  CODACY_PROJECT_TOKEN='xxxxxxxxxxxxx'|cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage .
This will send the coverage report to codacy.

Thanks for your help @pedrorijo91 . 👍

**Comment by Fire-Brand** [comment]
Trying to use an environment variable but with not success.

Here is what i've tried:
**1)**
```javascript
//1)
"test-with-coverage": "CODACY_PROJECT_TOKEN=1234567890 jest --coverage || true && cat ./coverage/lcov.info | codacy-coverage"

//2)
"test-with-coverage": "jest --coverage || true && cat ./coverage/lcov.info | CODACY_PROJECT_TOKEN=1234567890 codacy-coverage"

//3)
"test-with-coverage": "jest --coverage || true && CODACY_PROJECT_TOKEN=1234567890 | cat ./coverage/lcov.info | codacy-coverage"
```
(Also tried every option with single quotes on the token, e.g '1234567890')

All gave the same result: 
```javascript
[error] "2019-02-13T12:55:05.485Z"  'Error sending coverage'
[error] "2019-02-13T12:55:05.487Z"  Error: Token is required
    at Object.module.exports [as handleInput] (myProject/node_modules/codacy-coverage/lib/handleInput.js:22:35)
    at Socket.<anonymous> (myProject/node_modules/codacy-coverage/bin/codacy-coverage.js:48:20)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

What Am i missing?

P.S. I'm using `"jest-cli": "21.2.1"` and `"babel-jest": "21.2.0"`

**Comment by Fire-Brand** [comment]
@pedrorijo91 Any ideas?

**Comment by pedrorijo91** [comment]
maybe @rtfpessoa can help here
