### ISSUE TITLE
Use the correct accountToken

### ISSUE THREAD

**Issue by enrtama** [codacy/node-codacy-coverage#55]
I'm having troubles when sending the reports (lcov.info generated by JEST) to codacy-coverage:

**Token incorrect**
`cat coverage/lcov.info | codacy-coverage
[error] "2017-08-15T18:13:51.688Z"  'Status Code [404] - Error [{"error":"not found"}]'
[error] "2017-08-15T18:13:51.691Z"  'Error sending coverage'
[error] "2017-08-15T18:13:51.691Z"  Error: Expected Successful Status Code, but got [404]
    at /usr/local/lib/node_modules/codacy-coverage/lib/reporter.js:101:23`

In order to avoid this:

Go "Account" > "API Tokens" (copy the string in the input)

When triggering test action from package.json, the **accountToken** needs to be the correct one. Add the token copied above into this action:

`"test": "node scripts/test.js --env=jsdom --coverage && cat ./coverage/lcov.info | codacy-coverage --accountToken <TOKEN> --username <USERNAME> --projectName <PROJECT_NAME>"`

In the official docs, the account token that you add is the Project API Token, this is wrong!!!

**Comment by rtfpessoa** [comment]
Hi @enrtama, can you extend a bit more about exactly what is the problem you are experiencing?

**Comment by enrtama** [comment]
Hi @rtfpessoa, I've edited the content above, I hope It's helpful

**Comment by rtfpessoa** [comment]
I am sorry that our docs were not clear enough. I made some changes to highlight the tokens and how you can get them.
Can you take a look and let me know if it is more clear now?

**Comment by enrtama** [comment]
Yeah! Clear enough now, thank you very much for updating it.
I hope people don't have troubles with it anymore.

**Comment by rtfpessoa** [comment]
Thanks for your heads up.

Let us know if you have any other questions.
