### ISSUE TITLE
Vulnerability in non-direct dependency

### ISSUE THREAD

**Issue by pkosiec** [codacy/node-codacy-coverage#57]
Hi, I'm using your library and I've just been notified about security issue in one of your non-direct dependencies - `hoek` library.

![image](https://user-images.githubusercontent.com/7155799/39329922-2a2bf90a-49a0-11e8-8f5a-1c8da207733d.png)

It is used by your direct deps:
- `topo`
- `joi`
-`hawk`

I've just checked them and for all of them there are newer versions which fixed this security issue.
Could you please upgrade deps and make a new release?

Thanks!

**Comment by rtfpessoa** [comment]
@pkosiec thanks for the heads up. Will look into it.
