### ISSUE TITLE
Add .vue support in the coverage report

### ISSUE THREAD

**Issue by tsauvajon** [codacy/node-codacy-coverage#61]
I am building applications with the [Vue.js](https://vuejs.org/) front-end framework.
Jest is able to test the `.vue` files (that contain javascript), providing the same coverage reports as any `.js` or `.ts` files.

On the Codacy platform these files are purely and simply ignored; but they are also excluded from code coverage. In any application you can expect a big part of the percentage of JavaScript code to be located in the `.vue` files. Hence, the % coverage displayed on the platform is misleading.

Without the need for static analysis on `.vue` files (I use one of Codacy's competitors for this), it stops me (and probably other people) from using Codacy's coverage because of this.

I'm not sure if that's on the coverage provider side or on the web platform side (or both), but just adding these `.vue` files to the coverage recap, without any other Codacy feature, would be a huge plus for us.

**Comment by rtfpessoa** [comment]
@tsauvajon thanks for the suggestion. I will pass this to the product team so they can prioritise this since most of the changes need to be done on the product side and not in this tool.

**Comment by rtfpessoa** [comment]
Sorry for the delay, but we made it. We finally also support `.vue` and `.jsm`.
