### ISSUE TITLE
Dependency on Node >=8.12.0

### ISSUE THREAD

**Issue by juancarlosfarah** [codacy/node-codacy-coverage#71]
### node.js Version (2.5.x / etc)

v8.11.1

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

macOS 10.14

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Install should succeed.

### Actual Behavior

Getting the following error.

```
yarn add -D codacy-coverage
yarn add v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error topo@3.0.2: The engine "node" is incompatible with this module. Expected version ">=8.12.0". Got "8.11.1"
error Found incompatible module
```

I just wanted to point out that installation is failing on Node less than `8.12` due to a dependency on `topo` through `joi`. This is fixed with an upgrade to `8.12`, but I do not believe that the dependency on Node `v8.12` is documented.

**Comment by rtfpessoa** [comment]
@juancarlosfarah thanks for the heads up will update the docs.
