### ISSUE TITLE
Upload Jacoco coverage reports to Codacy

### ISSUE THREAD

**Issue by Chaitanya-Chatla** [codacy/node-codacy-coverage#72]
I would like to upload coverage reports related to other languages (Ex: Jacoco reports for Java) using this package. Currently, it only supports coverage uploads for javascript.

**Comment by rtfpessoa** [comment]
@Chaitanya-Chatla this tools support all languages but only the format LCOV. For jacoco you need to use https://github.com/codacy/codacy-coverage-reporter.
