### ISSUE TITLE
Error while sending coverage using mocha 

### ISSUE THREAD

**Issue by vjoshihumancare** [codacy/node-codacy-coverage#75]
Hi,
I am trying to send coverage to codecy using mocha on windows machine which is my local machine.
I am using following command 
istanbul cover ./node_modules/mocha/bin/_mocha ./test --report lcovonly -- -R spec && type ./coverage/lcov.info | codacy-coverage --token <token> && rm -rf ./coverage

However  I get following error message . Any idea what this means ? 

 name: 'ValidationError',
  details:
   [ { message: '"value" is not allowed to be empty',
       path: [],
       type: 'any.empty',
       context: [Object] } ],
  _object: '',
  annotate: [Function] }
[error] "2018-12-27T00:50:29.650Z"  'Error sending coverage'
[error] "2018-12-27T00:50:29.650Z"  { ValidationError: "value" is not allowed to be empty
    at Object.exports.process (C:

**Comment by rtfpessoa** [comment]
@vjoshihumancare the message is pretty cryptic. Can you run the tool with `--debug` and provide the full output.

Also, from  first look when you invoke `... | codacy-coverage --token <missing-token> && ...` I am guessing you removed the token to post here but you placed it there when invoking.

**Comment by finaxar-arthur** [comment]
I used this command

```
"jest --passWithNoTests --coverage && cat ./coverage/lcov.info | codacy-coverage --language typescript --debug"
```

with `CI` and `CODACY_PROJECT_TOKEN` set as environment variables. I get the same error as the person above.

**Comment by ljmf00** [comment]
Hey @vjoshihumancare and @finaxar-arthur ,

Can you check if the `stdin` is send something to the reporter? It seems you are passing an empty buffer. Check the content of your coverage output file.

Thanks,
Luis

**Comment by mrfyda** [comment]
Closed due to inactivity.
