### ISSUE TITLE
Unable to work with new organization repositories.

### ISSUE THREAD

**Issue by JounQin** [codacy/node-codacy-coverage#88]
### node.js Version

`v12.14.1`

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

`Darwin JounQin-MBP 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

### Expected Behavior

Work like previous projects.

### Actual Behavior

I provided `CODACY_ACCOUNT_TOKEN` and `CODACY_PROJECT_TOKEN` environments, but `name` and `projectName` is still required, but I didn't figure out what should I pass through.

### Reproducible Test Case

`cat ./coverage/lcov.info | codacy-coverage -u JounQin -n rx-ts/pkgr`

https://github.com/rx-ts/pkgr/runs/380810917?check_suite_focus=true#step:7:50

**Comment by mrfyda** [comment]
@JounQin we're deprecating this reporter in favor of https://github.com/codacy/codacy-coverage-reporter. a new version with support for using account token is available now!

the new reporter is language agnostic, easier to install and contains many bug fixes that were never ported to this reporter.
